services:
  contao_bootstrap.core.core_subscriber:
    class: ContaoBootstrap\Core\Subscriber\CoreSubscriber
    arguments:
      - "@contao_bootstrap.environment"
    tags:
      - { name: kernel.event_subscriber }

  contao_bootstrap.environment:
    class: ContaoBootstrap\Core\Environment
    arguments:
      - "@contao_bootstrap.config"
      - "@contao_bootstrap.icon_set"
      - "@event_dispatcher"

  contao_bootstrap.config:
    class: ContaoBootstrap\Core\Config\ArrayConfig

  contao_bootstrap.config.type_manager:
    class: ContaoBootstrap\Core\Config\TypeManager
    arguments:
      - "@contao_bootstrap.config"
      - "@contao_bootstrap.config.types"

  contao_bootstrap.config.types:
    factory: ["@contao_bootstrap.config.type_factory", createAll]

  contao_bootstrap.config.type_factory:
    class: ContaoBootstrap\Core\Config\TypeFactory
    arguments:
      - "@contao_bootstrap.config"

  contao_bootstrap.icon_set:
    class: ContaoBootstrap\Core\IconSet
