services:
  contao_bootstrap.environment:
    class: ContaoBootstrap\Core\Environment
    arguments:
      - '@event_dispatcher'

  contao_bootstrap.config:
    class: ContaoBootstrap\Core\Config\ArrayConfig
    arguments:
      - '%contao_bootstrap.config%'

  contao_bootstrap.view.template_modifier:
    class: ContaoBootstrap\Core\View\Template\ModifierChain
    arguments:
      - []

  contao_bootstrap.core.dca.content:
    class: ContaoBootstrap\Core\DataContainer\Content
    arguments:
      - '@contao_bootstrap.environment'

  contao_bootstrap.core.dca.layout:
    class: ContaoBootstrap\Core\DataContainer\Layout
    arguments:
      - '@contao_bootstrap.environment'

  contao_bootstrap.core.helper.color_rotate:
    class: ContaoBootstrap\Core\Helper\ColorRotate
