services:
  contao_bootstrap.core.core_subscriber:
    class: ContaoBootstrap\Core\Subscriber\CoreSubscriber
    arguments:
      - "@contao_bootstrap.environment"
    tags:
      - { name: kernel.event_subscriber }

  contao_bootstrap.environment:
    class: ContaoBootstrap\Core\Environment
    arguments:
      - "@contao_bootstrap.config"
      - "@contao_bootstrap.icon_set"
      - "@event_dispatcher"

  contao_bootstrap.config:
    class: ContaoBootstrap\Core\Config\ArrayConfig

  contao_bootstrap.icon_set:
    class: ContaoBootstrap\Core\IconSet
