services:
  contao_bootstrap.environment:
    class: ContaoBootstrap\Core\Environment
    arguments:
      - "@contao_bootstrap.config"
      - "@contao_bootstrap.icon_set"

  contao_bootstrap.config:
    class: ContaoBootstrap\Core\Config\ArrayConfig
    arguments:
      - "%contao_bootstrap.config.config%"

  contao_bootstrap.config.type_manager:
    class: ContaoBootstrap\Core\Config\TypeManager
    arguments:
      - "@contao_bootstrap.config"

  contao_bootstrap.config.types:
    class: ContaoBootstrap\Core\Config\TypeFactory
    factory: ["@contao_bootstrap.config.type_factory", createAll]

  contao_bootstrap.config.type_factory:
    class: ContaoBootstrap\Core\Config\TypeFactory
    arguments:
      - "@contao_bootstrap.config"

  contao_bootstrap.icon_set:
    class: ContaoBootstrap\Core\IconSet

  contao_bootstrap.config.types.icon_set:
    class: ContaoBootstrap\Core\Config\Type\IconSetType
    tags:
      - { name: contao_bootstrap.config.type}
